services:
  exchange-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: exchange-api
    working_dir: /app
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '27017:27017'

volumes:
  node_modules:
